In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math
from datetime import datetime

from scipy.spatial import cKDTree
from scipy.optimize import curve_fit
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

import warnings

warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv("data/total_add_velocity_weighted_average.csv")
target = pd.read_csv("data/target.csv")
water = pd.read_csv("data/water_velocity2016.csv")
wind = pd.read_csv("data/wind_velocity2016.csv")

# Make predict model

In [3]:
reg = data.copy()
reg = reg.iloc[:,4:10]

In [4]:
features = ['water_u', 'water_v', 'wind_u', 'wind_v']
target_d_long = 'd_long'
target_d_lati = 'd_lati'

In [5]:
X_train, X_test, y_train_long, y_test_long, y_train_lati, y_test_lati = train_test_split(
    reg[features], reg[target_d_long], reg[target_d_lati], test_size=0.2, random_state=42)

In [6]:
model_d_long = lgb.LGBMRegressor()
model_d_lati = lgb.LGBMRegressor()

In [7]:
model_d_long.fit(X_train, y_train_long)
model_d_lati.fit(X_train, y_train_lati)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000351 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1020
[LightGBM] [Info] Number of data points in the train set: 12651, number of used features: 4
[LightGBM] [Info] Start training from score 0.015105
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000128 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1020
[LightGBM] [Info] Number of data points in the train set: 12651, number of used features: 4
[LightGBM] [Info] Start training from score 0.006790

LGBMRegressor()

In [8]:
predictions_d_long = model_d_long.predict(X_test)
predictions_d_lati = model_d_lati.predict(X_test)

In [9]:
rmse_d_long = math.sqrt(mean_squared_error(y_test_long, predictions_d_long))
rmse_d_lati = math.sqrt(mean_squared_error(y_test_lati, predictions_d_lati))

print(f'RMSE for d_long: {rmse_d_long}')
print(f'RMSE for d_lati: {rmse_d_lati}')

RMSE for d_long: 0.04379742249993648
RMSE for d_lati: 0.0346956785806289

# Preprocessing target data

In [10]:
drifter = [1,2,3,4,5,6,7]
t = []
lon = []
lat = []
for i in range(len(target)):
    start_date = datetime(2016, 1, 1)
    y = int(target.iloc[i][0])
    m = int(target.iloc[i][1])
    d = int(target.iloc[i][2])
    target_date = datetime(y, m, d)
    
    h = ((target.iloc[i][3] // 6) + 1) * 0.25
    x = (target_date - start_date).days
    x += h
    x -=1
    t.append(x)
    
    lon_deg = target.iloc[i][5]
    lon_min = target.iloc[i][6]
    
    lat_deg = target.iloc[i][7]
    lat_min = target.iloc[i][8]
    
    _lon = lon_deg + (lon_min / 60)
    _lat = lat_deg + (lat_min / 60)
    
    lon.append(_lon)
    lat.append(_lat)    
    
target["drifter"] = drifter    
target["time"] = t
target["longitude"] = lon
target["latitude"] = lat
target

,year,month,day,hour,minute,longitude_degree,longitude_minute,latitude_degree,latitude_minute,drifter,time,longitude,latitude
0,2016,3,13,11,49,127,4.310,32,30.442,1,71.50,127.071833,32.507367
1,2016,3,15,20,15,126,36.949,33,45.559,2,74.00,126.615817,33.759317
2,2016,3,19,12,1,129,16.916,34,56.978,3,77.75,129.281933,34.949633
3,2016,3,19,12,38,129,12.744,34,59.200,4,77.75,129.212400,34.986667
4,2016,7,15,15,40,127,4.468,32,30.976,5,195.75,127.074467,32.516267
5,2016,7,18,12,48,129,17.834,34,55.305,6,198.75,129.297233,34.921750
6,2016,7,20,1,49,129,23.897,37,33.155,7,200.25,129.398283,37.552583

In [11]:
main = target.iloc[:,9:]
main

   drifter    time   longitude   latitude
0        1   71.50  127.071833  32.507367
1        2   74.00  126.615817  33.759317
2        3   77.75  129.281933  34.949633
3        4   77.75  129.212400  34.986667
4        5  195.75  127.074467  32.516267
5        6  198.75  129.297233  34.921750
6        7  200.25  129.398283  37.552583

In [12]:
water = water.fillna(0)
wind = wind.fillna(0)

In [13]:
main["water_u"] = 0
main["water_v"] = 0
main["wind_u"] = 0
main["wind_v"] = 0
main['d_long'] = 0
main['d_lati'] = 0

In [14]:
# Create a grid of longitude and latitude from the water DataFrame
grid = water[['longitude', 'latitude']].drop_duplicates().values

# Create a KD-Tree for efficient nearest neighbor search
kdtree = cKDTree(grid)

# Function to find the 4 closest vertices for a given point
def find_closest_vertices(row):
    point = np.array([row['longitude'], row['latitude']])
    # Query the KD-Tree to find the 4 closest vertices
    _, indices = kdtree.query(point, k=4)
    return indices

# Apply the function to the main DataFrame to find the 4 closest vertices for each point
main['closest_vertices'] = main.apply(find_closest_vertices, axis=1)

In [15]:
u = []
v = []
for i in range(len(main)):
    x = water.loc[water["time"] == main.iloc[i][1]]
    w_u = []
    w_v = []
    w_d = []
    for j in main.iloc[i][-1]:
        d = ((main.iloc[i][2] - x.iloc[j][1])**2 + (main.iloc[i][3] - x.iloc[j][2])**2) ** 0.5
        w_u.append(x.iloc[j][-2])
        w_v.append(x.iloc[j][-1])
        w_d.append(d)

    # weithged average
    total_weight = sum(w_d)
    weighted_u = sum(w_u[i] * w_d[i] for i in range(len(w_d))) / total_weight
    weighted_v = sum(w_v[i] * w_d[i] for i in range(len(w_d))) / total_weight

    u.append(weighted_u)
    v.append(weighted_v)

main["water_u"] = u
main["water_v"] = v

In [16]:
# Create a grid of longitude and latitude from the water DataFrame
grid2 = wind[['longitude', 'latitude']].drop_duplicates().values

# Create a KD-Tree for efficient nearest neighbor search
kdtree = cKDTree(grid2)

# Function to find the 4 closest vertices for a given point
def find_closest_vertices(row):
    point = np.array([row['longitude'], row['latitude']])
    # Query the KD-Tree to find the 4 closest vertices
    _, indices = kdtree.query(point, k=4)
    return indices

# Apply the function to the main DataFrame to find the 4 closest vertices for each point
main['closest_vertices2'] = main.apply(find_closest_vertices, axis=1)

In [17]:
u = []
v = []
for i in range(len(main)):
    x = wind.loc[wind["time"] == main.iloc[i][1]]
    w_u = []
    w_v = []
    w_d = []
    for j in main.iloc[i][-1]:
        d = ((main.iloc[i][2] - x.iloc[j][1])**2 + (main.iloc[i][3] - x.iloc[j][2])**2) ** 0.5
        w_u.append(x.iloc[j][-2])
        w_v.append(x.iloc[j][-1])
        w_d.append(d)

    # weighted_average
    total_weight = sum(w_d)
    weighted_u = sum(w_u[i] * w_d[i] for i in range(len(w_d))) / total_weight
    weighted_v = sum(w_v[i] * w_d[i] for i in range(len(w_d))) / total_weight

    u.append(weighted_u)
    v.append(weighted_v)

main["wind_u"] = u
main["wind_v"] = v

In [18]:
main = main.iloc[:,:-2]
main

,drifter,time,longitude,latitude,water_u,water_v,wind_u,wind_v,d_long,d_lati
0,1,71.50,127.071833,32.507367,-0.011915,0.225438,-3.647036,0.083368,0,0
1,2,74.00,126.615817,33.759317,0.009959,0.054703,-1.908922,-4.001212,0,0
2,3,77.75,129.281933,34.949633,0.104336,0.172520,2.419362,-3.250100,0,0
3,4,77.75,129.212400,34.986667,0.119752,0.199445,2.470042,-3.347662,0,0
4,5,195.75,127.074467,32.516267,-0.016639,0.143890,-0.781448,-1.167220,0,0
5,6,198.75,129.297233,34.921750,0.168963,0.236222,3.850836,1.386833,0,0
6,7,200.25,129.398283,37.552583,0.049902,0.074426,-4.100182,2.380681,0,0

In [19]:
new_main = pd.DataFrame()

# 원본 데이터 프레임의 각 행을 100번 복사하여 추가하고, 조건에 따라 열 값을 설정합니다.
for i in range(len(main)):
    for j in range(365*4):
        row = main.iloc[i].copy()
        row['time'] += j * 0.25
        
        if j > 0:
            row['longitude'] = 0
            row['latitude'] = 0
            row['water_u'] = 0
            row['water_v'] = 0
            row['wind_u'] = 0
            row['wind_v'] = 0
            row['d_long'] = 0
            row['d_lati'] = 0
            
        new_main = pd.concat([new_main, row.to_frame().T], ignore_index=True)

In [20]:
drifter_1 = new_main.loc[new_main["drifter"] == 1].reset_index(drop=True)
drifter_2 = new_main.loc[new_main["drifter"] == 2].reset_index(drop=True)
drifter_3 = new_main.loc[new_main["drifter"] == 3].reset_index(drop=True)
drifter_4 = new_main.loc[new_main["drifter"] == 4].reset_index(drop=True)
drifter_5 = new_main.loc[new_main["drifter"] == 5].reset_index(drop=True)
drifter_6 = new_main.loc[new_main["drifter"] == 6].reset_index(drop=True)
drifter_7 = new_main.loc[new_main["drifter"] == 7].reset_index(drop=True)

In [21]:
result = pd.DataFrame()
drifter_lst = [drifter_1, drifter_2, drifter_3, drifter_4,
              drifter_5, drifter_6, drifter_7]

In [22]:
for df in drifter_lst:

    data = df

    # Create a grid of longitude and latitude from the water DataFrame
    grid = water[['longitude', 'latitude']].drop_duplicates().values

    # Create a KD-Tree for efficient nearest neighbor search
    kdtree = cKDTree(grid)

    # Function to find the 4 closest vertices for a given point
    def find_closest_vertices(row):
        point = np.array([row['longitude'], row['latitude']])
        # Query the KD-Tree to find the 4 closest vertices
        _, indices = kdtree.query(point, k=4)
        return indices

    for i in range(len(data)-1):
        # 예측
        features = [data.iloc[i][4], data.iloc[i][5], data.iloc[i][6], data.iloc[i][7]]
        _d_long = model_d_long.predict([features])
        _d_lati = model_d_lati.predict([features])

        # 예측값 할당
        data.iloc[i][-2] = _d_long
        data.iloc[i][-1] = _d_lati

        # 예측한 값으로 다음 위도 경도 설정
        data.iloc[i+1][2] = data.iloc[i][2] + data.iloc[i][-2]
        data.iloc[i+1][3] = data.iloc[i][3] + data.iloc[i][-1]

        near_lst = find_closest_vertices(data.iloc[i+1])

        x = water.loc[water["time"] == data.iloc[i][1]]
        w_u = []
        w_v = []
        w_d = []
        for j in near_lst:
            d = ((data.iloc[i][2] - x.iloc[j][1])**2 + (data.iloc[i][3] - x.iloc[j][2])**2) ** 0.5
            w_u.append(x.iloc[j][-2])
            w_v.append(x.iloc[j][-1])
            w_d.append(d)

        # weithged average
        total_weight = sum(w_d)
        weighted_u = sum(w_u[i] * w_d[i] for i in range(len(w_d))) / total_weight
        weighted_v = sum(w_v[i] * w_d[i] for i in range(len(w_d))) / total_weight

        data.iloc[i+1][4] = weighted_u
        data.iloc[i+1][5] = weighted_v

    # Create a grid of longitude and latitude from the water DataFrame
    grid2 = wind[['longitude', 'latitude']].drop_duplicates().values

    # Create a KD-Tree for efficient nearest neighbor search
    kdtree = cKDTree(grid2)

    # Function to find the 4 closest vertices for a given point
    def find_closest_vertices(row):
        point = np.array([row['longitude'], row['latitude']])
        # Query the KD-Tree to find the 4 closest vertices
        _, indices = kdtree.query(point, k=4)
        return indices

    for i in range(len(data)-1):
        near_lst = find_closest_vertices(data.iloc[i+1])

        x = wind.loc[wind["time"] == data.iloc[i][1]]
        w_u = []
        w_v = []
        w_d = []
        for j in near_lst:
            d = ((data.iloc[i][2] - x.iloc[j][1])**2 + (data.iloc[i][3] - x.iloc[j][2])**2) ** 0.5
            w_u.append(x.iloc[j][-2])
            w_v.append(x.iloc[j][-1])
            w_d.append(d)

        # weithged average
        total_weight = sum(w_d)
        weighted_u = sum(w_u[i] * w_d[i] for i in range(len(w_d))) / total_weight
        weighted_v = sum(w_v[i] * w_d[i] for i in range(len(w_d))) / total_weight

        data.iloc[i+1][6] = weighted_u
        data.iloc[i+1][7] = weighted_v
    
    result = pd.concat([result, data], ignore_index=True)

In [23]:
result

,drifter,time,longitude,latitude,water_u,water_v,wind_u,wind_v,d_long,d_lati
0,1.0,71.50,127.071833,32.507367,-0.011915,0.225438,-3.647036,0.083368,-0.004070,0.040605
1,1.0,71.75,127.067763,32.547971,-0.011915,0.225438,-3.647036,0.083368,-0.008634,0.037970
2,1.0,72.00,127.059129,32.585941,0.006102,0.239998,-1.586870,3.182891,-0.000533,0.045885
3,1.0,72.25,127.058596,32.631826,0.056210,0.221386,0.512616,1.828651,0.019086,0.041837
4,1.0,72.50,127.077682,32.673663,0.069692,0.169748,-0.125662,0.398060,0.027161,0.036997
...,...,...,...,...,...,...,...,...,...,...
10215,7.0,564.00,151.969097,36.663483,-0.163438,-0.089072,1.798779,1.971181,-0.053062,-0.029251
10216,7.0,564.25,151.916035,36.634231,-0.149573,-0.089338,-0.374233,2.145070,-0.053013,-0.032415
10217,7.0,564.50,151.863022,36.601816,-0.089377,0.006335,-2.478339,3.602263,-0.027717,-0.010948
10218,7.0,564.75,151.835305,36.590868,-0.061048,0.047977,-4.511387,3.964434,-0.017364,-0.000421
10219,7.0,565.00,151.817940,36.590447,-0.013090,-0.031844,1.755816,6.195522,0.000000,0.000000

In [24]:
result.describe()

,drifter,time,longitude,latitude,water_u,water_v,wind_u,wind_v,d_long,d_lati
count,10220.000000,10220.000000,10220.000000,10220.000000,10220.000000,10220.000000,10220.000000,10220.000000,10220.000000,10220.000000
mean,4.000000,310.339286,142.667277,34.522524,0.072148,0.003685,0.894432,-0.678196,0.018102,-0.004478
std,2.000098,121.713215,11.526710,5.463370,0.256620,0.190072,4.944121,5.252300,0.049161,0.040872
min,1.000000,71.500000,126.615817,14.604317,-1.245813,-1.334180,-23.018505,-19.977711,-0.080218,-0.130947
25%,2.000000,219.000000,135.026426,34.296967,-0.037286,-0.054275,-2.199025,-4.068833,-0.008151,-0.016646
50%,4.000000,310.250000,139.596814,35.867156,0.000000,0.000000,0.541492,-0.519563,0.016031,-0.001469
75%,6.000000,401.500000,145.929221,37.210663,0.126298,0.083922,3.840166,2.494425,0.039180,0.009613
max,7.000000,565.000000,183.141127,42.404062,1.651031,1.101477,17.470640,17.647302,0.140901,0.145329

In [27]:
result.to_csv("data/result_365days.csv", index = False)